enabled: true
about_label: About
about_header: 'pShots Photography'
social_networks:
  -
    icon: fa-twitter
    label: Twitter
    url: 'https://twitter.com/@karkeraprasad'
  -
    icon: fa-facebook
    label: Facebook
    url: 'https://www.facebook.com/pshotspk'
contact_header: 'Get in touch'
social_header: 'Follow me on ...'
favicon: favicon.png
