enabled: true
about_label: About
about_header: 'Magna feugiat sed adipiscing'
about_content: 'Nulla consequat, ex ut suscipit rutrum, mi dolor tincidunt erat, et scelerisque turpis ipsum eget quis orci mattis aliquet. Maecenas fringilla et ante at lorem et ipsum. Dolor nulla eu bibendum sapien. Donec non pharetra dui. Nulla consequat, ex ut suscipit rutrum, mi dolor tincidunt erat, et scelerisque turpis ipsum.'
copyright: '&copy; Unttled. Design: <a href="http://html5up.net">HTML5 UP</a>. Images: <a href="https://pixabay.com/en/users/Oldiefan-740865/">Oldiefan</a>.'
social_networks:
  -
    icon: fa-twitter
    label: Twitter
    url: 'https://www.twitter.com/'
  -
    icon: fa-facebook
    label: Facebook
    url: 'https://www.facebook.com/'
  -
    icon: fa-instagram
    label: Instagram
    url: 'https://www.instagram.com/'
  -
    icon: fa-github
    label: GitHub
    url: 'https://www.github.com/'
  -
    icon: fa-dribbble
    label: Dribbble
    url: 'https://www.dribbble.com/'
  -
    icon: fa-linkedin
    label: LinkedIn
    url: 'https://www.linkedin.com/'
contact_header: 'Get in touch'
social_header: 'Follow me on ...'
favicon: favicon.png
